### ISSUE TITLE
Case for rust-vk-middle

### ISSUE THREAD

**Issue by kvark** [gfx-rs/portability#1]
@JohnColanduoni wrote
> I was taking a crack at this some time ago by trying to encode the interface a Vulkan driver library (ICD) provides into Rust. My approach was to create a trait that embodied an implementation and include associated types for each dispatchable object. The interface code handles dereferencing handles to backend-specific types and the ICD structure requirements, and the synchronization requirements are (hopefully correctly) represented in the trait signatures via mutability of references. Ideally there would be no unsafe code in individual backends (at least on the Vulkan side of things).

>Implementing the Vulkan API directly (without porting the standard Vulkan loader from https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers) wouldn't be much different, and most of the glue functions could be re-used.

> It's at https://github.com/JohnColanduoni/rust-vk-middle, with the interesting parts mostly in https://github.com/JohnColanduoni/rust-vk-middle/blob/master/src/middle/src/icd/mod.rs.

**Comment by JohnColanduoni** [comment]
If you're interested in any of that code I think the best thing to do would be to move it here in any case. I was lazy and just had bindgen run at build time, but you've already integrated the bindgen output.

**Comment by msiglreith** [comment]
Is this issue still relevant?

**Comment by kvark** [comment]
Having another look at this, the `Impl` trait seems to mostly copy our `Backend`, and ICD API has been implemented in #8. Appears to be safe to close it. @JohnColanduoni please comment if we missed anything to salvage!
