### ISSUE TITLE
Creating zeroed backend types might crash

### ISSUE THREAD

**Issue by fkaa** [gfx-rs/portability#103]
In some places (eg. [`gfxBindBufferMemory`](https://github.com/gfx-rs/portability/blob/master/libportability-gfx/src/impls.rs#L1147)) we create a zeroed type of the backend type and `mem::replace` it. If the backend type has a `Drop` impl rust will try to drop this zeroed type which might lead to bad things.

I'm not really sure what the intent of the `mem::replace` call is, does anyone know?

**Comment by kvark** [comment]
I think the reason for `mem::replace` is that we need to move the `Unbound` buffer out and then get the bound buffer to put back in. Without replace you can either de-reference or unbox, which is not useful here.

But overall, we should totally not drop random zeroed content ;)
