### ISSUE TITLE
Faster bound resource expectation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/portability#115]
As our buffers and images are all stored as `enum { Bound, Unbound }`, it requires a match/branch on each and every access. This may show up in the profiles, even if a lower priority than using iterators everywhere. We need a build mode that avoids those branches and just transmutes the thing where it's expected.

**Comment by msiglreith** [comment]
The Bound <-> Unbound difference is nice for typesafety but will probably fall apart for sparse resources at some point. So we could merge those again or keep it in HAL and adjust it for portability in case we go with the BAL approach.

**Comment by kvark** [comment]
This is not a problem as of https://github.com/gfx-rs/gfx/pull/2518
