### ISSUE TITLE
Question, Would OpenGL bakend would be added? Such as (Web GL 2.0).

### ISSUE THREAD

**Issue by lygstate** [gfx-rs/portability#19]

**Comment by msiglreith** [comment]
Hello,
we will add/have an OpenGL backend in gfx, but most likely not 100% feature complete with the Vulkan API. The lower the GL the more `Feature` flags we need. At the end, it depends on how the Vulkan portability extension (or whatever mechanism will be used for defining the portability subset) will look like. Without special consideration for GL (e.g combined texture/samplers only, rest as feature, ..) it probably won't be able to have an 100% portablility implementation for GL in my opinion.

**Comment by kvark** [comment]
GL is already operational in gfx HAL, even though the support is fairly basic.
Vulkan portability will only defined GL (and D3D11) limitations as a follow-up extensions, most likely. Until then, we'll have to manage those internally and provide the feedback to the group.
The target GL versions are: desktop GL 2.1, ES 2.0, WebGL 1.0
