### ISSUE TITLE
R.I.P.

### ISSUE THREAD

**Issue by procedural** [gfx-rs/portability#213]
http://kvark.github.io/web/gpu/native/2020/05/03/point-of-webgpu-native.html

This is the most spactacular self-roast I've read this year so far. At least at one point this lib could run DOTA, that's all Valve cares about when they claim Vulkan is better than other APIs, in a sense you did your job and now it can die peacefully.

R.I.P. portability initiative implementation, 2017-2020.

**Comment by grovesNL** [comment]
Hi 👋 We're still actively developing gfx-portability in this repo and [gfx](https://github.com/gfx-rs/gfx) (where most of the actual implementation is located).

Vulkan Portability and WebGPU have different trade-offs (e.g. ease-of-use, performance, security, portability guarantees), so there are valid use cases for both. It's up to users to decide which API they'd prefer based on these trade-offs.

@kvark talked about [some of these trade-offs at FOSDEM](https://fosdem.org/2020/schedule/event/rust_webgpu/), which included a great slide to show the performance vs. ease of use trade-off for some of the existing graphics APIs:
![image](https://user-images.githubusercontent.com/2113872/81408181-55eb9800-9117-11ea-9cdc-5d953c50ce8d.png)

[wgpu](https://github.com/gfx-rs/wgpu) is also implemented with gfx. So as we add features to support the implementation of WebGPU we'll be improving the Portability implementation and vice versa. Interestingly we can run both the Vulkan Portability CTS and WebGPU CTS over most of the core logic.
