### ISSUE TITLE
how to install this on icd on windows?

### ISSUE THREAD

**Issue by Luvar123** [gfx-rs/portability#257]

**Comment by kvark** [comment]
I generally just run with `VK_ICD_FILENAMES` pointing to the JSON file. There are probably other ways, check out https://github.com/KhronosGroup/Vulkan-Loader/blob/main/docs/LoaderInterfaceArchitecture.md

**Comment by Luvar123** [comment]
and how to compile?

**Comment by kvark** [comment]
Follow the CI scripts for releases, or download one of the releases hosted by Github already.
See the script https://github.com/gfx-rs/portability/blob/master/.github/workflows/release.yml
